### ISSUE TITLE
Provide RSS / Atom feed

### ISSUE THREAD

**Issue by refset** [juxt/astro-website#34]
There was [a question](https://juxt-oss.zulipchat.com/#narrow/stream/298045-juxt-misc/topic/juxt.20blog/near/375914991) about whether there was an RSS feed available but it seems we never added/enabled it to this astro setup.

We definitely had it setup at some point previously, to syndicate with Planet Clojure:
https://github.com/ghoseb/planet.clojure/blob/fe269a2c09c0d4d554ff58d4eae2a4bf4bc06a75/clojure/config.ini#L3417-L3420

In case its helpful to refer to, we configured a blog feed for the xtdb.com site (also using astro) with `astrojs/rss` in [this commit](https://github.com/xtdb/astro-site/commit/bcae40466fcc03be084f70a9048cc817a08162c4) (presumably just following the official docs https://docs.astro.build/en/guides/rss/) - let me know if someone wants access to that org/repo but essentially the commit is just...

Creating `src/pages/blog.xml.js`:
```
import rss from '@astrojs/rss';
import { getCollection } from 'astro:content';

export async function get(context) {
  const blog = await getCollection('blog');
  return rss({
    title: 'XTDB Blog',
    description: 'Engineering insights and development updates',
    site: context.site,
    items: blog.map((post) => ({
      title: post.data.title,
      pubDate: post.data.date,
      description: post.data.summary,
      link: `/blog/${post.slug}`,
    })),

    trailingSlash: false,
    customData: "<author><name>JUXT Ltd</name><email>hello@xtdb.com</email></author>"
  });
}
```

Updating `src/layouts/main.astro` with:
`<link rel="alternate" type="application/rss+xml" href="/blog.xml" title="XTDB Blog">`

Updating `export default defineConfig({` in `astro.config.mjs` to include:
`site: 'https://xtdb.com'` 

And adding `"@astrojs/rss": "^2.3.2"` to the package.json.

**Comment by armincerf** [comment]
I briefly looked into this, a couple of things:

config should be at src/pages/blog.xml.js and be:
```
import rss from '@astrojs/rss'
import { getCollection } from 'astro:content'

export async function get(context) {
  const blog = await getCollection('blog')
  return rss({
    title: 'JUXT Blog',
    description:
      'JUXT is a UK based software firm and the creators of the bi-temporal graph database XTDB. This blog contains various posts written by our employees. The opinions expressed in the posts are those of the author, and not necessarily of JUXT.',
    site: context.site,
    items: blog.map((post) => ({
      title: post.data.title,
      pubDate: post.data.date,
      description: post.data.summary,
      link: `/blog/${post.slug}`
    })),

    trailingSlash: false,
    customData:
      '<author><name>JUXT Ltd</name><email>info@juxt.pro</email></author>'
  })
}
```

but this will only work when we move everything to be a [content collection](https://docs.astro.build/en/guides/content-collections/)

**Comment by Akeboshiwind** [comment]
I've added a PR to add two feeds: `feed.xml` & `clojureplanet.xml`.
It works with the current version of the site but will need to be migrated when/if we move to collections
